### ISSUE TITLE
Evoker not working

### ISSUE THREAD

**Issue by Twirxx** [2072/Decursive#11]
Seems not to work with new Evoker class

**Comment by lholbert** [comment]
Potential workaround until it gets fixed.

Custom spells/items
- Check box "Allow internal macro editing for the above spell"
- Enter "Living Flame" for the name (NOTE: Naturalize(Green) is not recognized by DCR, marks it as "unavailable")
- Click "Okay"

In the list below select "Living Flame"
- Set up the afflictions, Magic and Poison
- Edit the macro, where it says "Living Flame", replace that with "Naturalize(Green)"
- Click Accept

DCR will complain that the spell in the macro does not match, and that the cooldown will not be tracked correctly.  This is the tradeoff.

If talented, one can also manually add "Cauterizing Flame", no macro is needed for this one, just set up the afflictions correctly (curse, disease, poison ... no bleed available).
NOTE: I set Spell Priority for CF to -10, so that it becomes my "blue"/right click

In theory, this looks like it all should work, though the caveat is, the CD on Naturalize will not be tracked, one will have to do that manually.

I'm off to find a mob with a poison to test this out

**Comment by lholbert** [comment]
To follow up can confirm, that the above did work with Naturalize on poison debuffs.
To reiterate, since we are "fooling" the current engine, the CD will not be tracked by DCR.  But at least the functionality is there.

**Comment by 2072** [comment]
Thanks for all the details. I just saw this issue now, I was focused on the issues listed on the historic page: https://www.wowace.com/projects/decursive/issue

Is everything ok now?
