### ISSUE TITLE
LUA error happening often

### ISSUE THREAD

**Issue by RejectKid** [2072/Decursive#13]
![image](https://user-images.githubusercontent.com/6117898/224508906-b50a61d7-801b-4f96-a43f-f41cc18f496b.png)

Could copy/pasta text but i have this.  it also occurs so often that blizz warning pops up to disable addon.  

Love your addon and have used for many years! thanks!

**Comment by 2072** [comment]
Please, read the message in orange that is clipped in your screenshot. Decursive is merely telling you that another add-on is causing many errors and that you should take care of this problem but it's not Decursive.

The add-on that is causing the issue is trying to use a deprecated API called GetActivityInfo (Decursive does not use this API). You can try to find which add-on is causing this by enabling LUA error reporting in your WoW interface option, or look for the text GetActivityInfo in your add-on folder.
