### ISSUE TITLE
Possible to disable blacklist?

### ISSUE THREAD

**Issue by Meivyn** [2072/Decursive#18]
Is this even possible with your current code?

https://github.com/2072/Decursive/blob/5f9a738c5b1c4b5b8c8eaffbe531919978803be4/Dcr_Events.lua#L779-L792

I don't get the point of that feature, and as a healer, I find it actually very annoying, I had to look into your code and disable that manually (but I'd rather have it fixed in the addon than do it every single update). I'd like to know if it could be possibly implemented in a future release.

My point is that I don't want Decursive to auto-blacklist people who are out of the line of sight, because I'd rather move and find them than let them "notice they have to move near me" and die from the debuff. I don't get the point of that feature honestly. Would appreciate it if you could explain a bit. 

I would not mind making PR to make it *at the very least* configurable, but testing this stuff is actually not very straightforward.

**Comment by 2072** [comment]
This feature is a a legacy feature from the time when Decursive was a 'just smash the same button add-on' used in big 40 people raids groups where several players were removing debuffs at the same time so that it would not get stuck on out of sight targets. It was ported over as the idea was that one should not have to care about who each box is and just click each box.

I'm not sure if people rely on this feature, I'll add an option to disable it.

**Comment by teelolws** [comment]
We can't detect distance to other players inside instances anymore unfortunately, but maybe could just make it reset after a couple of seconds of trying?

**Comment by 2072** [comment]
There is a "seconds on the blacklist" option in the General tab, now it can be set to 0 to effectively disable the blacklisting feature completely.
