### ISSUE TITLE
[Request] Add #showtooltip to the Decursive macro

### ISSUE THREAD

**Issue by robmonte** [2072/Decursive#7]
Not sure if you'd agree with this, but I think it would be nice to have `#showtooltip Remove Lesser Curse` (or Remove Curse for retail) in the macro text the addon creates. Personally I just find it a lot easier to manage my macros by their macro icon, and doing this would give it the spell icon of the remove curse ability appropriately. Plus the question marks are ugly. 😀 

Let me know your thoughts.

**Comment by 2072** [comment]
This is not required since the question mark icon is used which does the same. the thing is that since this is a mouse over macro you need to have a target under your cursor to see the actual icon. Normally you do not need to have this macro on your toolbar since it is bound to a key (that you set in the /decursive option panel).
I'm not sure if many people are using this anymore, it's a remnant of when Decursive was doing the targeting automatically, you just had to smash that key to cleanse everyone who needed it...

**Comment by robmonte** [comment]
I know you just closed this, but looking back at my original wording I can see I didn't explain my desire very clearly. There's another (admittedly small) benefit of adding `#showtooltip` and it is that it actually adds the appropriate spell icon to the macro when viewing the macro menu.

The list can get cluttered and sometimes question-mark icons are necessary for complex macros that involve multiple abilities. Due to that, I think it would be helpful to avoid showing a question-mark in the macro menu whenever possible - such as any macro that will be tied to a single ability like Remove Lesser Curse.

**Comment by 2072** [comment]
Ok so the change would be to add showtooltip when there is only one ability
in the macro because adding it when there are several would prevent the
icon from changing with the modifier.
I'm curious, how are you using this macro? Is it not better to disable the
creation of the macro in the settings of Decursive and use your own instead
or do you use it across several characters?

**Comment by robmonte** [comment]
To be honest I don't really remember because it's been a long time since I played WoW. When Wrath launches if I rediscover what drove me to making this issue, then I'll report back for clarification, but I can understand if you think this isn't worth the timing considering either way.
